FROM docker.io/wolframresearch/wolframengine

USER root

RUN useradd -m wljs

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    git \
    nginx \
    expect \
    curl \
 && curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
 && apt-get install -y nodejs \
 && apt-get install -y \
    ca-certificates \
    gnupg  \
    build-essential \
    cmake \
    ninja-build \
    pkg-config \
    clang \
    lld \
    lldb \
 && apt-get install nvidia-cuda-toolkit -y \
 && apt-get install nvidia-utils-580-server -y \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

COPY container/wljs-routes /etc/nginx/sites-available/default
COPY container/proxy-snippet.conf /etc/nginx/snippets/proxy.conf

RUN mkdir -p /wljs
COPY ./ /wljs/

COPY container/run.sh /run.sh
RUN chmod +x /run.sh

CMD /run.sh
