<|"WL"->{
  "https://github.com/KirillBelovTest/Objects" -> "master",
  "https://github.com/JerryI/Internal" -> "master",
  "https://github.com/JerryI/TCPServer" -> "master",
  "https://github.com/JerryI/HTTPHandler" -> "master",
  "https://github.com/JerryI/WebSocketHandler" -> "master",
  "https://github.com/JerryI/CSocketListener" -> "master",
  "https://github.com/JerryI/wl-wlx" -> "master",
  "https://github.com/JerryI/wl-misc" -> "main",
  "https://github.com/lshifr/LetWL" -> "master"
},
"WLJS"->{
  "https://github.com/JerryI/wljs-editor" -> "base",
  "https://github.com/JerryI/Mathematica-ThreeJS-graphics-engine" -> "base",
  "https://github.com/JerryI/wljs-sharedlib-d3" -> "base",
  "https://github.com/JerryI/wljs-sharedlib-mk" -> "base",
  "https://github.com/JerryI/wljs-sharedlib-three" -> "base",
  "https://github.com/JerryI/wljs-graphics-d3" -> "base",
  "https://github.com/JerryI/wljs-html-support" -> "base",
  "https://github.com/JerryI/wljs-inputs" -> "base",
  "https://github.com/JerryI/wljs-interpreter" -> "base",
  "https://github.com/JerryI/wljs-js-support" -> "base",
  "https://github.com/JerryI/wljs-markdown-support" -> "base",
  "https://github.com/JerryI/wljs-magic-support" -> "base",
  "https://github.com/JerryI/wljs-plotly" -> "base",
  "https://github.com/JerryI/wljs-cells" -> "base",
  "https://github.com/JerryI/wljs-revealjs" -> "base",
  "https://github.com/JerryI/wljs-wlx-support" -> "base",
  "https://github.com/JerryI/wljs-mermaid-support" -> "base",
  "https://github.com/JerryI/wljs-snippets" -> "base",
  "https://github.com/JerryI/wljs-alt-cell-controls" -> "base",
  "https://github.com/JerryI/wljs-print-redirect-fix" -> "base",
  "https://github.com/JerryI/wljs-export-html" -> "base",
  "https://github.com/JerryI/wljs-manipulate" -> "base",
  "https://github.com/JerryI/wljs-sound" -> "base",
  "https://github.com/JerryI/wljs-video" -> "base",
  "https://github.com/JerryI/wljs-templates" -> "base",
  "https://github.com/JerryI/wljs-xterm" -> "base",
  "https://github.com/JerryI/wljs-excalidraw" -> "base",
  "https://github.com/JerryI/wljs-toc" -> "base",
  "https://github.com/JerryI/wljs-wxf-accelerator" -> "base",
  "https://github.com/JerryI/wljs-neuralnet" -> "base",
  "https://github.com/JerryI/wljs-docs-archive" -> "base",
  "https://github.com/JerryI/wljs-demos-archive" -> "base",
  "https://github.com/JerryI/wljs-debugger" -> "base",
  "https://github.com/JerryI/wljs-api" -> "base"
}|>